### ISSUE TITLE
To do

### ISSUE THREAD

**Issue by TheoVerhelst** [WizardCorp/WizardCorpDotCom#3]
* [x] Allow administrators to add an institution (that will be a big form with plenty of fields);
* [x] Create Hotels.xml and Users.xml file, make the parser read them;
* [x] Implement `MySqlDatabase::searchInInstitutions`;
* [x] Make use of the SQL procedures;
* [x] Implement the R* requests.
* [x] Implement the database constraints

**Comment by StanIsAdmin** [comment]
All of these are done and the whole project has changed so I think I'll just close the issue.
